import { APP_PREFIX_PATH } from 'constants/route.constant';
import {
  NAV_ITEM_TYPE_TITLE,
  NAV_ITEM_TYPE_COLLAPSE,
  NAV_ITEM_TYPE_ITEM,
} from 'constants/navigation.constant';
import { ADMIN, USER } from 'constants/roles.constant';

const appsNavigationConfig = [
  {
    key: 'apps',
    path: '',
    title: 'Menu',
    translateKey: 'nav.apps',
    icon: 'apps',
    type: NAV_ITEM_TYPE_TITLE, // title | collapse | item
    authority: [ADMIN, USER],
    subMenu: [
      {
        key: 'apps.main',
        path: `${APP_PREFIX_PATH}/main/dashboard`,
        title: 'Main',
        translateKey: 'nav.appsMain.dashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM, // item
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
          key: 'apps.battery',
          path: '',
          title: 'Battery',
          translateKey: 'nav.appsBattery.main',
          icon: 'battery',
          type: NAV_ITEM_TYPE_COLLAPSE,
          authority: [ADMIN, USER],
          subMenu: [
              {
                  key: 'appsBattery.dashboard',
                  path: `${APP_PREFIX_PATH}/battery/dashboard`,
                  title: 'Batteries',
                  translateKey: 'nav.appsBattery.dashboard',
                  icon: '',
                  type: NAV_ITEM_TYPE_ITEM,
                  authority: [ADMIN, USER],
                  subMenu: [],
              },
              {
                  key: 'appsBattery.new',
                  path: `${APP_PREFIX_PATH}/battery/new`,
                  title: 'Create Battery',
                  translateKey: 'nav.appsBattery.new',
                  icon: '',
                  type: NAV_ITEM_TYPE_ITEM,
                  authority: [ADMIN, USER],
                  subMenu: [],
              },
              {
                  key: 'appsBattery.upload',
                  path: `${APP_PREFIX_PATH}/battery/upload`,
                  title: 'Upload Battery',
                  translateKey: 'nav.appsBattery.upload',
                  icon: '',
                  type: NAV_ITEM_TYPE_ITEM,
                  authority: [ADMIN, USER],
                  subMenu: [],
              },
              {
                  key: 'appsBattery.warranty',
                  path: `${APP_PREFIX_PATH}/battery/warranty`,
                  title: 'Warranty Registrations',
                  translateKey: 'nav.appsBattery.upload',
                  icon: '',
                  type: NAV_ITEM_TYPE_ITEM,
                  authority: [ADMIN, USER],
                  subMenu: [],
              },
              {
                  key: 'appsBattery.qrcode',
                  path: `${APP_PREFIX_PATH}/battery/qr-code`,
                  title: 'Generate QR Code',
                  translateKey: 'nav.appsBattery.qrcode',
                  icon: '',
                  type: NAV_ITEM_TYPE_ITEM,
                  authority: [ADMIN, USER],
                  subMenu: [],
              }
          ],
      },
      {
          key: 'apps.company',
          path: '',
          title: 'Company',
          translateKey: 'nav.appsCompany.main',
          icon: 'company',
          type: NAV_ITEM_TYPE_COLLAPSE,
          authority: [ADMIN, USER],
          subMenu: [
              {
                  key: 'appsCompany.dashboard',
                  path: `${APP_PREFIX_PATH}/company/dashboard`,
                  title: 'Companies',
                  translateKey: 'nav.appsCompany.dashboard',
                  icon: '',
                  type: NAV_ITEM_TYPE_ITEM,
                  authority: [ADMIN, USER],
                  subMenu: [],
              },
              {
                  key: 'appsCompany.new',
                  path: `${APP_PREFIX_PATH}/company/new`,
                  title: 'Create Company',
                  translateKey: 'nav.company.new',
                  icon: '',
                  type: NAV_ITEM_TYPE_ITEM,
                  authority: [ADMIN, USER],
                  subMenu: [],
              },
              {
                  key: 'appsCompany.orderHistory',
                  path: `${APP_PREFIX_PATH}/company/order-history`,
                  title: 'Order History',
                  translateKey: 'nav.company.orderHistory',
                  icon: '',
                  type: NAV_ITEM_TYPE_ITEM,
                  authority: [ADMIN, USER],
                  subMenu: [],
              },
              {
                  key: 'appsCompany.deliveryOrders',
                  path: `${APP_PREFIX_PATH}/company/delivery-order`,
                  title: 'Delivery Orders',
                  translateKey: 'nav.appsCompany.deliveryOrders',
                  icon: '',
                  type: NAV_ITEM_TYPE_ITEM,
                  authority: [ADMIN, USER],
                  subMenu: [],
              },
              {
                  key: 'appsCompany.uploadDO',
                  path: `${APP_PREFIX_PATH}/company/upload-do`,
                  title: 'Upload Delivery Orders',
                  translateKey: 'nav.appsCompany.uploadDO',
                  icon: '',
                  type: NAV_ITEM_TYPE_ITEM,
                  authority: [ADMIN, USER],
                  subMenu: [],
              }
          ],
      },
      {
          key: 'apps.users',
          path: '',
          title: 'Users',
          translateKey: 'nav.appsUsers.main',
          icon: 'users',
          type: NAV_ITEM_TYPE_COLLAPSE,
          authority: [ADMIN, USER],
          subMenu: [
              {
                  key: 'appsUsers.dashboard',
                  path: `${APP_PREFIX_PATH}/users/dashboard`,
                  title: 'Internal Users',
                  translateKey: 'nav.appsUsers.dashboard',
                  icon: '',
                  type: NAV_ITEM_TYPE_ITEM,
                  authority: [ADMIN, USER],
                  subMenu: [],
              },
              {
                  key: 'appsUsers.endUser',
                  path: `${APP_PREFIX_PATH}/users/end-users`,
                  title: 'End Users',
                  translateKey: 'nav.appsUsers.endUser',
                  icon: '',
                  type: NAV_ITEM_TYPE_ITEM,
                  authority: [ADMIN, USER],
                  subMenu: [],
              }
          ],
      },
      {
          key: 'apps.settings',
          path: '',
          title: 'Settings',
          translateKey: 'nav.appsSettings.main',
          icon: 'settings',
          type: NAV_ITEM_TYPE_COLLAPSE,
          authority: [ADMIN, USER],
          subMenu: [
              {
                  key: 'appsSettings.profile',
                  path: `${APP_PREFIX_PATH}/settings/profile`,
                  title: 'My Profile',
                  translateKey: 'nav.appsSettings.profile',
                  icon: '',
                  type: NAV_ITEM_TYPE_ITEM,
                  authority: [ADMIN, USER],
                  subMenu: [],
              },
              {
                  key: 'appsSettings.logout',
                  path: `${APP_PREFIX_PATH}/users/logout`,
                  title: 'Logout',
                  translateKey: 'nav.appsSettings.logout',
                  icon: '',
                  type: NAV_ITEM_TYPE_ITEM,
                  authority: [ADMIN, USER],
                  subMenu: [],
              }
          ],
      },
    ],
  },
];

export default appsNavigationConfig;
